name: CurrentTime
version: ${pluginVersion}
description: ${pluginDescription}
main: me.tibinonest.plugins.currenttime.CurrentTime
api-version: 1.13
authors: [ TibiNonEst ]
website: https://tibinonest.me
commands:
  currenttime:
    description: Plugin reload command
    usage: /<command>
    permission: currenttime.reload
    permission-message: You do not have permission to use this command.
    aliases: [ct]
permissions:
  currenttime.reload:
    description: Reloads the CurrentTime plugin.
    default: op
  currenttime.*:
    description: Wildcard permission
    default: op
    children:
      currenttime.reload: true
